#!/usr/bin/env bash
# Bash script that displays the PID along with the process name,
# of processes whose name contain the word bash.

# pgrep is used to search for and list the process IDs (PIDs) of
# processes based on certain criteria.

# Bash script that uses the pgrep command to find processes
# containing the word "bash"

# This script uses the "-l" option to display the process ID (PID) along
# with the process name.
pgrep -l bash
