#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100
# with occasional "FizzBuzz" & "Buzz"

# The for loop that iterates from 1 to 100, incrementing
# the variable i by 1 in each iteration.
# The ((i % 3 == 0)) checks if the number is a multiple of 3.
# The ((i % 5 == 0)) checks if the number is a multiple of 5.
# The && represents logical AND, so ((i % 3 == 0)) && ((i % 5 == 0))
# checks if the number is a multiple of both 3 and 5.
# The else block is executed if none of the previous conditions
# (Fizz, Buzz, or FizzBuzz) are true.
for ((i=1; i<=100; i++)); do
    if ((i % 3 == 0)) && ((i % 5 == 0)); then
        echo "FizzBuzz"
    elif ((i % 3 == 0)); then
        echo "Fizz"
    elif ((i % 5 == 0)); then
        echo "Buzz"
    else
        echo "$i"
    fi
done
