#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.

# This script uses a while loop to read each line of the /etc/passwd file,
# and the read command with the IFS (Internal Field Separator) set to ':' to
# extract the desired fields (username, user id, and home directory).
while IFS=':' read -r username x userid groupid home shell; do
    echo "$username:$userid:$home"
done < /etc/passwd

