#!/usr/bin/env bash
# This script is displaying "bad luck", "good luck" & "Best School"

# Counter to keep track of iterations
hour=0

# You should use [ $hour -lt 12 ] since you want to display
# hours from 0 to 11 (12 hours in total).
# Inside the loop, the minutes are echoed (printed to the console)
# from 1 to 59, and the value of $minute is incremented in each iteration.
while [ $hour -lt 12 ];
do
    echo "Hour: $hour"
    
    minute=1
    while [ $minute -le 59 ];
    do
        echo "$minute"
        ((minute++))
    done

    ((hour++))
done
