#!/usr/bin/env bash
# Bash script that displays content of current directory in a list format

# Skip hidden files.
# Extract part of the name after the first dash.
# Print the extracted part of the name.
for file in *
do
    if [[ $file == .* ]]; then
        continue
    fi

    part_of_name=${file#*-}

    echo "$part_of_name"
done
