#!/usr/bin/env bash
# Bash script that changes Home IP.

# Backup original /etc/hosts file
cp /etc/hosts /etc/hosts.backup

# Adds IP address to /etc/hosts
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
# Uncomment the following lines to revert changes
#cp -f /etc/hosts.backup /etc/hosts
#echo "Changes reverted. Check the results:"
#ping localhost
#ping facebook.com
