#!/usr/bin/env bash
# Script that displays all active IPv4 IPs on the machine.

# Check if eth0 has an IPv4 address
eth0_ip=$(ifconfig eth0 | awk '/inet / {print $2}' | cut -d ':' -f 2)

# Check if lo has an IPv4 address
lo_ip=$(ifconfig lo | awk '/inet / {print $2}' | cut -d ':' -f 2)

# Display the IPs
echo "$eth0_ip"
echo "$lo_ip"
